# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BANEFIREBASE' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BANEFIREBASE
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Core'

  target 'BANEFIREBASETests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BANEFIREBASEUITests' do
    # Pods for testing
  end

end
